config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'contacts/new'
    get 'contacts/create'
  end

  devise_for :admins, controllers: {
  	sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_scope :admin do
    post '/admins/guest_sign_in', to: 'admin/sessions#guest'
  end

  namespace :admin do
  	get 'top' => 'homes#top'
  	resources :users, only: [:index, :show, :edit, :update]
  	resources :posts
  	resources :genres, only: [:index, :create, :edit, :update]
  	resources :prefectures, only: [:edit, :update]
  	resources :areas, only: [:index, :create, :edit, :update]
    resources :contacts, only: [:index, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
  	sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  scope module: :public do
  	root 'homes#top'
  	get 'about' => 'homes#about'
  	get 'confirm' => 'users#confirm'
  	put 'confirm' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'follows' => 'relationships#follower', as: 'follows'
      get 'follows/timeline' => 'relationships#timeline'
      get 'followers' => 'relationships#followed', as: 'followers'
    end
  	resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :history
      end
    end
    get 'favorites' => 'favorites#index'
    resources :contacts, only: [:new, :create, :index, :show]
    post 'contacts/confirm' => 'contacts#confirm'
    resources :notifications, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :posts
	validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!

	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			redirect_to admin_genres_path, notice:'新ジャンルを登録しました'
		else
			@genres = Genre.all
			render :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
			redirect_to admin_genres_path, notice:'ジャンル名を編集しました'
		else
			render :edit
		end
	end

	private
	def genre_params
		params.require(:genre).permit(:name)
	end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<h1>ジャンル編集</h1>
<%= form_for(@genre, url: admin_genre_path(@genre)) do |f| %>
<%= render 'layouts/error_messages', resource: @genre %>
	<%= f.label :ジャンル名 %>
	<%= f.text_field :name %>
	<%= f.submit '変更する', class: "btn btn-primary btn-sm" %>
<% end %>

app/views/admin/genres/index.html.erb
<div class="col-xs-5">
	<h2>ジャンル一覧</h2>
	<table class="table">
		<thead>
			<tr>
				<td>ジャンル名</td>
				<td>投稿数</td>
				<td></td>
		<% @genres.each do |genre| %>
		<tbody>
			<tr>
				<td><%= link_to genre.name, posts_path(genre_id: genre.id) %></td>
				<td><%= genre.posts.count %></td>
				<td><%= link_to '編集する', edit_admin_genre_path(genre) %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
</div>

<div class="col-xs-7">
	<div class="alert alert-info">
		<h4>《ご利用方法》</h4>
		<p><strong>◎新たにジャンルを作成する場合</strong><br>　→　下記フォームより登録ください。</p>
		<p><strong>◎エリア名を変更する場合</strong><br>　→　左の一覧にある各ジャンル名の編集フォームにて変更ください。</p>
	</div>

	<h3>新規ジャンル登録</h3>
	<%= form_for(@genre, url: admin_genres_path) do |f| %>
	<%= render 'layouts/error_messages', resource: @genre %>
		<%= f.label :ジャンル名 %>
		<%= f.text_field :name %>　
		<%= f.submit '新たにジャンルを登録する', class: "btn btn-primary"%>
	<% end %>
</div>