config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'contacts/new'
    get 'contacts/create'
  end

  devise_for :admins, controllers: {
  	sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_scope :admin do
    post '/admins/guest_sign_in', to: 'admin/sessions#guest'
  end

  namespace :admin do
  	get 'top' => 'homes#top'
  	resources :users, only: [:index, :show, :edit, :update]
  	resources :posts
  	resources :genres, only: [:index, :create, :edit, :update]
  	resources :prefectures, only: [:edit, :update]
  	resources :areas, only: [:index, :create, :edit, :update]
    resources :contacts, only: [:index, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
  	sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  scope module: :public do
  	root 'homes#top'
  	get 'about' => 'homes#about'
  	get 'confirm' => 'users#confirm'
  	put 'confirm' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'follows' => 'relationships#follower', as: 'follows'
      get 'follows/timeline' => 'relationships#timeline'
      get 'followers' => 'relationships#followed', as: 'followers'
    end
  	resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :history
      end
    end
    get 'favorites' => 'favorites#index'
    resources :contacts, only: [:new, :create, :index, :show]
    post 'contacts/confirm' => 'contacts#confirm'
    resources :notifications, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ゲストログイン
  def self.guest
    find_or_create_by!(name: 'guest', email: 'guestuser@mail.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  has_many :posts
  attachment :image

  validates :name, presence: true
  validates :is_active, presence: true

  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: 'post'

  # 通知(active:アクションを起こす/passive:通知を受け取る)
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # フォロー通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?

      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 問い合わせ
  has_many :contacts

  # 閲覧履歴
  has_many :browsing_histories, dependent: :destroy

  # フォロー
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォロー済の場合はtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  #会員ステータス1＝会員のみログイン可
  def active_for_authentication?
    super && (self.is_active == 1)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_admin!

	def index
		# 検索窓
		if params[:keyword]
			@keyword = params[:keyword]
			users = []

			# 入力された値を区切ってキーワード毎に検索
			@keyword.split(/[[:blank:]]+/).each do |keyword|
				# 全半角スペース、先頭の空白に対応
				next if @keyword == ""
				users += User.where('name LIKE(?)', "%#{keyword}%")
			end
			# 重複している結果を削除
			users.uniq!
            # paginate_arrayメソッドで配列をページネーション
			@users = Kaminari.paginate_array(users).page(params[:page]).per(10)

		elsif
			@users = User.order(created_at: :desc).page(params[:page]).per(10)
		end
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to admin_user_path(@user), notice:'会員情報を更新しました'
		else
			render 'edit'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :is_active)
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1><%= attachment_image_tag @user, :image, format: "jpeg", fallback: "no_image.jpg", size:"50x50" %>
	<%= @user.name %>さんの会員ステータスの編集</h1>

<%= form_for(@user, url: admin_user_path) do |f| %>
<%= render 'layouts/error_messages', resource: @user %>

	<p>会員ステータス　
		<%= f.radio_button :is_active, 1 %>
		<%= f.label :is_active, "有効" %>
		<%= f.radio_button :is_active, 0 %>
		<%= f.label :is_active, "退会済み" %>
	</p>

	<p>ユーザー名　
		<%= f.text_field :name, class: "form-control" %>
	</p>
	<p>メールアドレス
		<%= f.text_field :email, class: "form-control" %>
	</p>

	<div>
		<%= f.submit "更新する", class: "btn btn-primary" %>
	</div>

<% end %>

app/views/admin/users/index.html.erb
<h2>会員一覧</h2>
<% if params[:keyword] %>
	<h2><%= @keyword %>の検索結果：<%= @users.count %>件ヒットしました</h2>
<% end %>
<div class="row">
	<div class="col-xs-3">
		<%= form_tag(admin_users_path, method: :get) do %>
            <p><%= text_field_tag :keyword, '', placeholder: "会員を検索", class: "form-control" %></p>

            <p><%= submit_tag '検索', class: "btn btn-primary btn-sm"  %></p>
            <p><%= link_to "全会員表示する", admin_users_path %></p>
        <% end %>
        
	</div>

	<div class="col-xs-9">

		<table class='table'>
		  <thead>
		    <tr>
		    	<th>会員ID</th>
		    	<th>登録日</th>
				<th>アカウント名</th>
				<th>会員ステータス</th>
				<th>投稿数</th>
				<th></th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @users.each do |user| %>
		      <tr>
		      	<td><%= user.id %></td>
		      	<td><%= user.created_at.strftime("%Y年%m月%d日 ") %>
		      	<td>
		      		<%= attachment_image_tag user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "30x30" %>
		      		<%= user.name %>
		      	</td>
		        <td>
		        	<% if user.is_active? %>
			        	<span><i class="fas fa-user-circle fa-lg"></i> 有効</span>
		        	<% else %>
			        	<span>退会</span>
			      	<% end %>
			    </td>
			    <td><%= user.posts.count %>
		        <td><%= link_to 'Show', admin_user_path(user) %></td>
		      </tr>
		    <% end %>
		    <%= paginate @users %>
		  </tbody>
		</table>
	</div>
</div>

app/views/admin/users/show.html.erb
<h3>会員ID：<%= @user.id %>
	<%= attachment_image_tag @user, :image, format: 'jpeg', fallback: "no_image.jpg", size: "30x30" %>
	<%= @user.name %>さんの Profile</h3><hr>
<div class="row">
		<p>会員ステータス：
			<% if @user.is_active? %>
		        <span><i class="fas fa-user-circle fa-lg"> 有効</i></span>
	        <% else %>
		       	<span>退会済</span>
		    <% end %>　
		    <%= link_to "編集する", edit_admin_user_path, class: "btn btn-primary btn-sm" %>
			　Follows：<%= @user.follower.count %>　Follower：<%= @user.followed.count %></p>
		<p>メールアドレス：<%= @user.email %>　</p>
		<p>おすすめ：<%= @user.recommend %></p>
		<p>自己紹介：<%= @user.introduction %></p>
		<p><%= link_to '会員一覧に戻る', admin_users_path, class: "btn btn-default" %></p>
</div>

<h2>User Post</h2>
<div class="row">
	<% @posts.each do |post| %>
	<div class="col-lg-3 col-sm-4">
		<%= link_to post_path(post) do %>
			<%= attachment_image_tag post, :image, format: "jpeg", fallback: "sample.jpg", size:"250x200" %>
		<% end %>
		<p><%= post.title %></p>
	</div>
	<% end %>
</div>