config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'contacts/new'
    get 'contacts/create'
  end

  devise_for :admins, controllers: {
  	sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_scope :admin do
    post '/admins/guest_sign_in', to: 'admin/sessions#guest'
  end

  namespace :admin do
  	get 'top' => 'homes#top'
  	resources :users, only: [:index, :show, :edit, :update]
  	resources :posts
  	resources :genres, only: [:index, :create, :edit, :update]
  	resources :prefectures, only: [:edit, :update]
  	resources :areas, only: [:index, :create, :edit, :update]
    resources :contacts, only: [:index, :edit, :update, :destroy]
  end

  devise_for :users, controllers: {
  	sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_scope :user do
    post '/users/guest_sign_in', to: 'public/sessions#new_guest'
  end

  scope module: :public do
  	root 'homes#top'
  	get 'about' => 'homes#about'
  	get 'confirm' => 'users#confirm'
  	put 'confirm' => 'users#withdraw'
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'follows' => 'relationships#follower', as: 'follows'
      get 'follows/timeline' => 'relationships#timeline'
      get 'followers' => 'relationships#followed', as: 'followers'
    end
  	resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get :history
      end
    end
    get 'favorites' => 'favorites#index'
    resources :contacts, only: [:new, :create, :index, :show]
    post 'contacts/confirm' => 'contacts#confirm'
    resources :notifications, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
  	<h4><%= resource.errors.count %>件のエラー:
    記入されてない箇所があります。</h4>
    <ul id ="error_explanation" >
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="page-header">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <% if admin_signed_in? %>
        <%= link_to admin_top_path do %>
         <h2><i class="fas fa-home"></i></h2>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <h2><i class="fas fa-walking fa-sm">Local</i></h2>
        <% end %>
      <% end %>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Localとは？', about_path %></li>
          <li><%= link_to 'マイページ', user_path(current_user) %></li>
          <li class="new">
            <%= link_to new_post_path do %>
              <i class="fas fa-plus"> 新規投稿</i>
            <% end %>
          </li>
          <li><%= link_to '投稿一覧', posts_path %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to '問い合わせ', new_contact_path %></li>
          <li><%= link_to(notifications_path) do %>
                <% if unchecked_notifications.any? %>
                  <span class="fa-stack">
                    <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1.7em;"></i>
                    <i class="fas fa-circle n-circle fa-stack-1x"></i>
                  </span>
                <% else %>
                  <i class="far fa-bell" style="font-size: 1.5em;"></i>
                <% end %>
              <% end %>
          </li>

        <% elsif admin_signed_in? %>
          <li><%= link_to '問い合わせ一覧', admin_contacts_path %></li>
          <li><%= link_to 'エリア一覧', admin_areas_path %></li>
          <li><%= link_to 'ジャンル一覧', admin_genres_path %></li>
          <li><%= link_to '会員一覧', admin_users_path %></li>
          <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
          </li>

        <% else %>
          <li><%= link_to 'Localとは？', about_path %></li>
          <li><%= link_to '投稿一覧', posts_path %></li>
          <li><%= link_to 'ログイン', new_user_session_path %></li>
          <li><%= link_to '新規登録', new_user_registration_path %></li>
          <li><%= link_to '問い合わせ', new_contact_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div id="slide">
	<span class="nav-icon">
		<i class="fas fa-search"></i>
		<p>検索</p>
	</span>

	<div class="slide-inner">
		<div>
			<h5>
				<span><i class="fas fa-angle-double-right"></i></span>
				キーワードで探す
			</h5>
            <%= form_tag(posts_path, method: :get) do %>
                <%= text_field_tag :keyword, '', placeholder: "キーワードで検索" %>
                <%= submit_tag '検索' %>
            <% end %>
		</div>
		<div>
			<h5>
				<span><i class="fas fa-angle-double-right"></i></span>
				ジャンルから探す
			</h5>
			<% genres.each do |genre| %>
				<%= link_to genre.name, posts_path(genre_id: genre.id) %>
			<% end %>
		</div>

		<div>
			<h5>
				<span><i class="fas fa-angle-double-right"></i></span>
				タグから探す
			</h5>
			<div id="tag_lists"><%= render 'layouts/tag_list', tags: tags %></div>

			<div class="more">
				<%= link_to_next_page tags, 'もっと見る', remote: true, id: 'view_more' %>
			</div>
		</div>

		<div class="area">
			<h5>
				<span><i class="fas fa-angle-double-right"></i></span>
				エリア / 都道府県から探す
			</h5>
			<% areas.each do |area| %>
				<p class="openBtn"><%= link_to area.name, posts_path(area_id: area.id) %>エリア
				</p>
				<p class="textArea">
					<% area.prefectures.each do |prefecture| %>
						<%= link_to prefecture.name, posts_path(prefecture_id: prefecture.id) %>
					<% end %>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/_tag_list.html.erb
<% tags.each do |tag| %>
	#<%= link_to tag.name, posts_path(tag_id: tag.id) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a1e5d906c0.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
  </head>

  <body>
    <!-- HEADER -->
    <%= render 'layouts/header' %>

    <main>
  
      <div class="container">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>

    </main>

    <footer class="fixed-bottom">
      <%= link_to new_admin_session_path do %>
        Copyright ©Local Inc. All Rights Reserved.
      <% end %>
    </footer>
  </body>
</html>

app/views/layouts/sidebar.js.erb
$('#tag_lists').append(`<%= j(render partial: 'layouts/tag_list',locals: { tags: @s_tags }) %>`);
$('#view_more').hide();

// append: 子要素を表示
// hide: すべてが表示されたらボタンを非表示に